apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: arjayfuentes24/gateway-miyembro:latest
          ports:
            - containerPort: 8222
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 8222
      targetPort: 8222
      nodePort: 30085 # Exposed on the Node (Accessible Locally)
  type: NodePort
  #type: ClusterIP  # Changed from NodePort to ClusterIP
